// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkT7rjLlM1wP3c8AdulQ0B6p6QyUCnbSU',
    appId: '1:681172329982:web:6ef9946ae27b365ce44caf',
    messagingSenderId: '681172329982',
    projectId: 'generative-rex',
    authDomain: 'generative-rex.firebaseapp.com',
    storageBucket: 'generative-rex.appspot.com',
    measurementId: 'G-WXXCLKFEJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1BezvdIGeJHcpP20OxQiVxbJQxUGElxc',
    appId: '1:681172329982:android:276cd28f4144668ae44caf',
    messagingSenderId: '681172329982',
    projectId: 'generative-rex',
    storageBucket: 'generative-rex.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXcwKU76tDUB4k0dSzpuLMjQRGS-_Wh1M',
    appId: '1:681172329982:ios:ad55352433b19079e44caf',
    messagingSenderId: '681172329982',
    projectId: 'generative-rex',
    storageBucket: 'generative-rex.appspot.com',
    iosBundleId: 'com.example.generativeAiGemini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXcwKU76tDUB4k0dSzpuLMjQRGS-_Wh1M',
    appId: '1:681172329982:ios:ad55352433b19079e44caf',
    messagingSenderId: '681172329982',
    projectId: 'generative-rex',
    storageBucket: 'generative-rex.appspot.com',
    iosBundleId: 'com.example.generativeAiGemini',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkT7rjLlM1wP3c8AdulQ0B6p6QyUCnbSU',
    appId: '1:681172329982:web:aa136b3ea342084ae44caf',
    messagingSenderId: '681172329982',
    projectId: 'generative-rex',
    authDomain: 'generative-rex.firebaseapp.com',
    storageBucket: 'generative-rex.appspot.com',
    measurementId: 'G-2R7BW9302V',
  );
}
